version: '3'
services:
  fauxpilot_app:
    build: .
    ports:
      - "80:5000"
    environment:
      - KEY_VAULT_URI=${KEY_VAULT_URI}
    env_file:
      - .env
    environment:
      - FLASK_APP=app.py
    command: flask run --host=0.0.0.0 --port=5000
